#!/bin/bash

# Job Application Tracker - Environment Setup Script
# This script generates a .env file from .env.example with auto-generated secrets
# and interactive prompts, preserving existing values where possible.

set -e

ENV_FILE=".env"
ENV_EXAMPLE=".env.example"

echo "=================================="
echo "Job Application Tracker Setup"
echo "=================================="
echo

# Check if .env.example exists
if [ ! -f "$ENV_EXAMPLE" ]; then
    echo "❌ ERROR: $ENV_EXAMPLE not found!"
    exit 1
fi

# Load existing values if .env exists
if [ -f "$ENV_FILE" ]; then
    echo "Found existing $ENV_FILE. Loading current values..."
    # Read existing values into a temporary file to source easily or grep
    # We'll use grep to find existing values
fi

get_input() {
    local var_name="$1"
    local prompt_text="$2"
    local default_val="$3"
    local current_val=""
    
    # Try to find current value in existing .env
    if [ -f "$ENV_FILE" ]; then
        current_val=$(grep "^$var_name=" "$ENV_FILE" | cut -d'=' -f2-)
        # Remove surrounding quotes if present
        current_val="${current_val%\"}"
        current_val="${current_val#\"}"
    fi

    local final_val=""

    if [ -n "$current_val" ]; then
        echo "Found existing $var_name: $current_val"
        read -p "Keep this value? [Y/n]: " keep_choice
        keep_choice=${keep_choice:-Y}
        if [[ "$keep_choice" =~ ^[Yy]$ ]]; then
            final_val="$current_val"
        fi
    fi

    if [ -z "$final_val" ]; then
        if [ -n "$default_val" ]; then
            read -p "$prompt_text [$default_val]: " user_input
            final_val="${user_input:-$default_val}"
        else
            read -p "$prompt_text: " user_input
            final_val="$user_input"
        fi
    fi
    
    # Export so it can be used later or substituting
    export "$var_name"="$final_val"
}

generate_secret() {
    local var_name="$1"
    local current_val=""

    if [ -f "$ENV_FILE" ]; then
        current_val=$(grep "^$var_name=" "$ENV_FILE" | cut -d'=' -f2-)
    fi

    if [ -n "$current_val" ] && [ "$current_val" != "<auto-generated>" ]; then
        echo "Found existing secret for $var_name."
        read -p "Keep existing secret? [Y/n]: " keep_choice
        keep_choice=${keep_choice:-Y}
        if [[ "$keep_choice" =~ ^[Yy]$ ]]; then
            export "$var_name"="$current_val"
            return
        fi
    fi

    echo "Generating new secret for $var_name..."
    export "$var_name"=$(openssl rand -base64 32)
}

echo "📝 Configuration prompts..."
echo

# App Host
get_input "APP_HOST" "Enter APP_HOST" "localhost:8080"

# App Env
get_input "APP_ENV" "Enter APP_ENV (development/production)" "development"

# Database
echo
echo "--- Database Configuration ---"
get_input "POSTGRES_DB" "Enter POSTGRES_DB" "job_tracker"
get_input "POSTGRES_USER" "Enter POSTGRES_USER" "tracker_user"
generate_secret "POSTGRES_PASSWORD"
get_input "POSTGRES_HOST" "Enter POSTGRES_HOST" "postgres"
get_input "POSTGRES_PORT" "Enter POSTGRES_PORT" "5432"

# Backend
echo
echo "--- Backend Configuration ---"
get_input "FLASK_ENV" "Enter FLASK_ENV" "development"
generate_secret "SECRET_KEY"

# CORS Origin - Auto-determine based on APP_HOST but allow override
# Ensure we prefer HTTPS unless localhost
DEFAULT_PROTOCOL="http"
if [[ "$APP_HOST" != *"localhost"* ]] && [[ "$APP_HOST" != *"127.0.0.1"* ]]; then
    DEFAULT_PROTOCOL="https"
fi
DEFAULT_CORS="$DEFAULT_PROTOCOL://$APP_HOST"

get_input "BACKEND_CORS_ORIGIN" "Enter BACKEND_CORS_ORIGIN" "$DEFAULT_CORS"

# Google Tag Manager
echo
echo "--- Google Tag Manager ---"
get_input "GTM_ID" "Enter Google Tag Manager ID (leave empty if none)" ""

# Google OAuth
echo
echo "--- Google OAuth Configuration ---"
get_input "GOOGLE_CLIENT_ID" "Enter Google Client ID" ""
get_input "GOOGLE_CLIENT_SECRET" "Enter Google Client Secret" ""

# File Uploads
echo
echo "--- File Uploads ---"
get_input "UPLOAD_DIR" "Enter UPLOAD_DIR" "/app/uploads"
get_input "MAX_UPLOAD_SIZE" "Enter MAX_UPLOAD_SIZE (bytes)" "10485760"
get_input "ALLOWED_EXTENSIONS" "Enter ALLOWED_EXTENSIONS" "pdf,docx,doc"

echo
echo "✅ Writing to .env file..."

# Write to file
# We use cats and heredoc to handle this cleanly, ensuring variables are substituted
cat > "$ENV_FILE" <<EOF
# Application
APP_HOST=$APP_HOST
APP_ENV=$APP_ENV

# Database
POSTGRES_DB=$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_PORT=$POSTGRES_PORT

# Backend
FLASK_ENV=$FLASK_ENV
SECRET_KEY=$SECRET_KEY
BACKEND_CORS_ORIGIN=$BACKEND_CORS_ORIGIN

# Google Tag Manager (optional in Phase 1)
GTM_ID=$GTM_ID

# File Uploads (Phase 2)
UPLOAD_DIR=$UPLOAD_DIR
MAX_UPLOAD_SIZE=$MAX_UPLOAD_SIZE
ALLOWED_EXTENSIONS=$ALLOWED_EXTENSIONS

# Google OAuth
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
EOF

echo
echo "=================================="
echo "✅ Setup Complete!"
echo "=================================="
echo
echo "Environment file created/updated: $ENV_FILE"
